### ISSUE TITLE
Test Resources and Databases

### ISSUE THREAD

**Issue by ccparkhill** [Microsoft/Reporting-Services-LoadTest#15]
Getting "BlobNotFound" "The specified blob does not exist" errors for both links:
https://rsload.blob.core.windows.net/load/largefiles
https://rsload.blob.core.windows.net/load/databases

**Comment by jtarquino** [comment]
Where are you seeing that error?

**Comment by ccparkhill** [comment]
When I click the links, possibly due to work firewall, though I get the same error on my phone.

**Comment by jtarquino** [comment]
Those links are not meant to be consumed directly, they are used by the automation to download database files

**Comment by ccparkhill** [comment]
I see, I haven't come across a reference to them yet, where are they called from?

I read that as you download the files and the CreateDataBase script from the folder in the link:
>  All the databases used in the tests can be found https://rsload.blob.core.windows.net/load/databases. In order to deploy them to your environment, you can run the CreateDataBase.sql script (located in that folder).

**Comment by jtarquino** [comment]
The references to the blob are in https://github.com/Microsoft/Reporting-Services-LoadTest/blob/master/ArmTemplate/SSRS-MultiMachine/azuredeploy.json

**Comment by ccparkhill** [comment]
Is that just for Azure? How can I get a hold of the databases for on-prem testing? Thanks

**Comment by jtarquino** [comment]
You need to use AzCopy to download the content from the blob https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy

**Comment by ccparkhill** [comment]
Great, thanks for your help.
