### ISSUE TITLE
Public blob no longer available

### ISSUE THREAD

**Issue by davidlyth** [Microsoft/Reporting-Services-LoadTest#16]
Docs talk about https://rsload.blob.core.windows.net/load/databases but that can't be found

**Comment by jtarquino** [comment]
The blob does exist , it is a "folder", the content need to be downloaded using AzCopy, the script https://rsload.blob.core.windows.net/azcopy/CopyAndattachDatabases.ps1 which you can access from a browser
For instance one of the files in the "folder" is https://rsload.blob.core.windows.net/load/databases/AdventureWorks_data.mdf
