### ISSUE TITLE
Error on entering  username/pwd on logon.aspx

### ISSUE THREAD

**Issue by sneevand** [Microsoft/Reporting-Services-LoadTest#2]
I get same error onclicking button regretting user or login

An error occurred while attempting to verify the user.Request for the permission of type 'System.Data.SqlClient.SqlClientPermission, System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' failed.

I am not sure whether its an issue or, only I am receiving the error

**Comment by jtarquino** [comment]
Would you mind to provide more details, the load test doesn't have a user login button or a logon.aspx page

**Comment by sneevand** [comment]
I was able to land on logon.aspx page; which contains below interface
User Name : TextBox
Password: TextBox
Button for Register User
Button for Logon User

When i click on either button i end up with below error
'System.Data.SqlClient.SqlClientPermission, System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' failed.

**Comment by jtarquino** [comment]
My guess is that you are referring to the custom security extension, which is hosted in https://github.com/Microsoft/Reporting-Services/tree/master/CustomSecuritySample (which is a different repo than this one)

Would you mind to confirm? if that is the case can you provide the repro details there, are you just following the instructions?

**Comment by sneevand** [comment]
You are right I am just following instruction provided; And it is custom security extension,; 

 How can I move the issue there?

**Comment by jtarquino** [comment]
Issue reported in the incorrect repo

**Comment by navjotrnaura** [comment]
I am facing the same problem, can you guide me to the repository or the link where i can get solution to this.

**Comment by Mauricio7705** [comment]
Hola, tengo el mismo problema. Alguno conoce la solucion? muchas gracias
